apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: thomaswimprine-runners-homelab
  namespace: actions-runner-system
  labels:
    app: thomaswimprine-runners
    environment: production
    cluster: homelab-test
spec:
  # Replicas managed by HorizontalRunnerAutoscaler (0-6 runners)

  template:
    metadata:
      labels:
        app: thomaswimprine-runners
        environment: production
        cluster: homelab-test

    spec:
      # Init container to setup tool cache permissions
      initContainers:
        - name: setup-toolcache
          image: busybox:1.36-uclibc
          command:
            - sh
            - -c
            - |
              set -e
              echo "Setting up tool cache directory..."
              mkdir -p /opt/hostedtoolcache
              chown -R 1000:1000 /opt/hostedtoolcache
              chmod 755 /opt/hostedtoolcache
              echo "Tool cache ready: $(ls -ld /opt/hostedtoolcache)"
          securityContext:
            runAsUser: 0
            runAsNonRoot: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
              add:
                - CHOWN
                - FOWNER
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: tool-cache
              mountPath: /opt/hostedtoolcache
            - name: tmp-init
              mountPath: /tmp
          resources:
            requests:
              cpu: "10m"
              memory: "16Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"

      # Custom pre-built runner image
      image: ghcr.io/thomaswimprine/actions-runner:latest
      imagePullPolicy: Always

      # Organization-level runners for ThomasWimprine org
      organization: ThomasWimprine

      # Runner labels for workflow targeting
      labels:
        - self-hosted
        - Linux
        - X64
        - ARM64
        - talos
        - homelab
        - arc

      # Explicitly disable DinD sidecar (Talos uses containerd only, no Docker)
      dockerEnabled: false

      # Environment variables
      env:
        - name: DISABLE_RUNNER_UPDATE
          value: "true"

      # Resource allocation for homelab cluster with autoscaling
      # Autoscale: 0-6 runners, 4Gi memory per runner
      resources:
        requests:
          cpu: "500m"
          memory: "4Gi"
        limits:
          cpu: "1000m"
          memory: "4Gi"

      # Volume mounts for runner
      volumeMounts:
        - name: work
          mountPath: /runner/_work
        - name: tmp
          mountPath: /tmp
        - name: tool-cache
          mountPath: /opt/hostedtoolcache

      # Volumes (ephemeral storage)
      volumes:
        - name: work
          emptyDir:
            sizeLimit: 10Gi
        - name: tmp
          emptyDir:
            sizeLimit: 1Gi
        - name: tool-cache
          emptyDir:
            sizeLimit: 5Gi
        - name: tmp-init
          emptyDir: {}

      # Use custom ServiceAccount with minimal RBAC
      serviceAccountName: thomaswimprine-runners-sa

      # Security context (restricted PSS compliant)
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault

      # Pod anti-affinity for distribution across nodes
      affinity:
        # Require scheduling on worker nodes only (exclude control-plane)
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
        # Spread pods across different nodes
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - thomaswimprine-runners
                topologyKey: kubernetes.io/hostname
